# Generated by Django 3.0.6 on 2020-06-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=30)),
                ('link', models.TextField()),
                ('image', models.TextField()),
                ('usd_price', models.IntegerField()),
                ('uah_price', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
