# Generated by Django 3.0.4 on 2020-06-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=30)),
                ('link', models.URLField()),
                ('usd_price', models.IntegerField()),
                ('uah_price', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('image_ref', models.URLField()),
                ('location', models.CharField(max_length=10, null=True)),
                ('type', models.TextField(null=True)),
                ('mileage', models.DecimalField(decimal_places=10, max_digits=10, null=True)),
                ('engine', models.TextField(null=True)),
                ('gearbox', models.TextField(null=True)),
                ('transmission', models.TextField(null=True)),
                ('color', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
