# Generated by Django 3.0.4 on 2020-06-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
