# Generated by Django 3.0.4 on 2020-06-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_list', '0002_auto_20200611_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color_val',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
