# Generated by Django 3.0.6 on 2020-06-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_list', '0003_auto_20200602_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_ref',
            field=models.CharField(max_length=20),
        ),
    ]
