# Generated by Django 3.0.4 on 2020-06-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_list', '0003_car_color_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_ref',
            field=models.URLField(null=True),
        ),
    ]
